TRUNCATE TABLE users RESTART IDENTITY CASCADE;
TRUNCATE TABLE candidates RESTART IDENTITY CASCADE;
TRUNCATE TABLE employers RESTART IDENTITY CASCADE;
TRUNCATE TABLE employees RESTART IDENTITY CASCADE;
TRUNCATE TABLE verification_codes RESTART IDENTITY CASCADE;
